testing: true

# Site settings
title: "TransTex"
description: "A jinja2 based latex templating tool"

baseurl: "/TransTex"

# url: "localhost:4000"

# Build settings
markdown: kramdown
permalink: pretty
