#!/bin/bash

if [[ ! -f $1.ttex ]] ; then
  echo "File \"$1.ttex\" does not exist, aborting."
  exit
fi

ttex="./ttex"
datafile=metavita.yml

tex=pdflatex
junk="*.aux *.log *.out"

includes=$(ls _includes)

makefilename="__ttbuild-Makefile"

echo -e "ttex = $ttex" > $makefilename
echo -e "datafile = $datafile" >> $makefilename
echo -e >> $makefilename
echo -n "includes =" >> $makefilename
for i in $includes; do
  echo -n " _includes/$i" >> $makefilename;
done
echo -e >> $makefilename
echo -e >> $makefilename
echo -e "$1.pdf: _tex/$1.tex _tex/vitastyle.sty" >> $makefilename
echo -e "\tcd _tex && \$(MAKE) -f $makefilename ../$1.pdf" >> $makefilename
echo -e >> $makefilename
echo -e "_tex/$1.tex: $1.ttex \$(datafile) \$(includes)" >> $makefilename
echo -e "\t\$(ttex) $1.ttex \$(datafile) _tex/$1.tex" >> $makefilename

echo -e "tex = $tex" > _tex/$makefilename
echo -e "junk = $junk" >> _tex/$makefilename
echo -e >> _tex/$makefilename
echo -e >> _tex/$makefilename
echo -e "../$1.pdf: $1.tex vitastyle.sty" >> _tex/$makefilename
echo -e "\t\$(tex) $1" >> _tex/$makefilename
echo -e "\t\$(tex) $1" >> _tex/$makefilename
echo -e "\tmv $1.pdf .." >> _tex/$makefilename
echo -e "\trm \$(junk)" >> _tex/$makefilename

make -f $makefilename $1.pdf

rm $makefilename
rm _tex/$makefilename

