#!/usr/local/bin/python

import os
import jinja2
import sys
import yaml

num_args = len(sys.argv)

if (num_args != 4):
    print "invalid syntax. command format:"
    print sys.argv[0], "<template filename> <data filename> <output filename>"
    sys.exit()
 
template_filename = sys.argv[1]
data_filename = sys.argv[2]
output_filename = sys.argv[3]

data = yaml.load(open(data_filename), Loader=yaml.Loader)

templateLoader = jinja2.FileSystemLoader( searchpath="" )

j_env = jinja2.Environment(
        loader=templateLoader, 
        trim_blocks=True,
        lstrip_blocks=True,
        variable_start_string='\\ttvar{',
        variable_end_string='}',
        block_start_string='\\ttblock{',
        block_end_string='}',
        comment_start_string='\\ttcomment{',
        comment_end_string='}')

template = j_env.get_template(template_filename)

out_f = open(output_filename, 'w')
out_f.write(template.render(data=data))

